text_sensor:

  - platform: template
    name: $device_name Uptime
    id: up_since
    icon: mdi:clock-start
    entity_category: diagnostic

  - platform: wifi_info
    ip_address:
      name: $device_name IP Address
 
sensor:

  - platform: uptime
    id: upsince_sensor
    update_interval: 30s
    on_raw_value:
      then:
        - text_sensor.template.publish:
            id: up_since
            state: !lambda |-
              int secs    = round(id(upsince_sensor).raw_state);
              int days    = secs / (24 * 3600);
              secs        = secs % (24 * 3600);
              int hours   = secs / 3600;
              secs        = secs % 3600;
              int minutes = secs /  60;
              secs        = secs % 60;
              return (
                (days ? to_string(days) + "d " : "") +
                (hours ? to_string(hours) + "h " : "") +
                (minutes ? to_string(minutes) + "m " : "") +
                (to_string(secs) + "s")
              ).c_str();
